id: P000751
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:40:54.894308
source_metadata:
  id: bdr:W1KG13698
  title: སངས་རྒྱས་ཆོས་ལུགས་ཀྱི་སྤྱི་དོན་གསར་དཔྱད་བློ་གསལ་འཇུག་ངོགས།
  author: ''
  volumes:
    86b3d180c816436cbacf25044cf24b27:
      image_group_id: I1KG13707
      title: ''
      volume_number: 1
      total_pages: 512
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
