id: ICB2E6044
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T11:43:27+00:00'
last_modified: '2022-06-07T13:38:01.998468+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13698
  title: སངས་རྒྱས་ཆོས་ལུགས་ཀྱི་སྤྱི་དོན་གསར་དཔྱད་བློ་གསལ་འཇུག་ངོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '6064':
      image_group_id: I1KG13707
      title: ''
      total_pages: 512
      order: 1
      base_file: 6064.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
